modLoader = "javafml"
loaderVersion = "[53,)"
license = "MIT License"
issueTrackerURL="https://github.com/PanSzelescik/colorize/issues"
[[mods]]
modId = "colorize"
version = "${version}"
displayName = "Colorize"
displayURL="https://www.curseforge.com/minecraft/mc-mods/colorize"
authors = "PanSzelescik"
description = '''
Right click on the dye on some blocks to color them!
'''
[[dependencies.colorize]]
modId = "forge"
mandatory = true
versionRange = "[53.0.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.colorize]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.colorize]]
modId = "jei"
mandatory = false
versionRange = "[19.8.5,)"
ordering = "NONE"
side = "BOTH"
