modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"
issueTrackerURL="https://github.com/PanSzelescik/colorize/issues"
[[mods]]
modId = "colorize"
version = "${version}"
displayName = "Colorize"
displayURL="https://www.curseforge.com/minecraft/mc-mods/colorize"
authors = "PanSzelescik"
description = '''
Right click on the dye on some blocks to color them!
'''
[[dependencies.colorize]]
modId = "neoforge"
type = "required"
versionRange = "[20.5.0-beta,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.colorize]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.colorize]]
modId = "jei"
type = "optional"
versionRange = "[18,)"
ordering = "NONE"
side = "BOTH"
