# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  release:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    uses: PanSzelescik/colorize/.github/workflows/build.yml@1.19.2
    steps:
    - name: Publish Forge to CurseForge and Modrinth
      uses: Kir-Antipov/mc-publish@v3.2
      with:
        modrinth-id: colorize
        modrinth-featured: true
        modrinth-unfeature-mode: subset
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        curseforge-id: 658780
        curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

        files-primary: forge/build/libs/!(*-@(dev|dev-shadow|sources|javadoc)).jar
        files-secondary: forge/build/libs/*-@(dev|dev-shadow|sources|javadoc).jar

        name: ""
        version-type: release

        loaders: |
          forge
        game-versions: |
          1.19.2
          1.19.1
          1.19
        java: |
          17
          18

        retry-attempts: 2
        retry-delay: 10000
        fail-mode: fail
    - name: Publish Fabric to CurseForge and Modrinth
      uses: Kir-Antipov/mc-publish@v3.2
      with:
        modrinth-id: colorize
        modrinth-featured: true
        modrinth-unfeature-mode: subset
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        curseforge-id: 658780
        curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

        files-primary: fabric/build/libs/!(*-@(dev|dev-shadow|sources|javadoc)).jar
        files-secondary: fabric/build/libs/*-@(dev|dev-shadow|sources|javadoc).jar

        name: ""
        version-type: release

        loaders: |
          fabric
          quilt
        game-versions: |
          1.19.2
          1.19.1
          1.19
          1.18.2
          1.18.1
          1.18
        java: |
          17
          18

        retry-attempts: 2
        retry-delay: 10000
        fail-mode: fail
